#SETTING BASE IMAGE
FROM mcr.microsoft.com/dotnet/sdk:8.0-preview AS base-image

#FROM HERE ON, THIS WILL BE THE DIRECTORY UNDER CONTEXT IN THE IMAGE
WORKDIR /App

#BRINGING ONLY DEPENDENCIES
COPY *.csproj ./

#FETCH ALL DEPENDENCIES
RUN dotnet restore

#COPY EVERYTHING
COPY . ./

#BUILD AND PUBLISH A RELEASE TO THE OUT FOLDER
RUN dotnet publish -c release -o out

#BUILD RUNTIME IMAGE (BUILD IMAGE IS NO MORE NEEDED, AS ALL FILES WERE COPIED, DEPENDENCIES PULLED AND PUBLISHED)
FROM mcr.microsoft.com/dotnet/aspnet:8.0-preview
WORKDIR /App
COPY --from=base-image /App/out .
ENTRYPOINT ["dotnet", "Microservices.Web.Client.dll"]
#CMD ["dotnet","run"]